const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 11,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      ciuntInStock: 33,
      description: "A popular free shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 12,
      brand: "Puma",
      rating: 4,
      numReviews: 12,
      ciuntInStock: 30,
      description: "A popular fit shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 7,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 18,
      ciuntInStock: 30,
      description: "A popular slim shirt",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 5,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      ciuntInStock: 28,
      description: "A popular fit pants",
    },
    {
      name: "Calassic Pants",
      slug: "calassic-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 9,
      brand: "Puma",
      rating: 4,
      numReviews: 15,
      ciuntInStock: 35,
      description: "A popular calassic pants",
    },
    {
      name: "Slim Pants",
      slug: "slim-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 7,
      brand: "Zara",
      rating: 3,
      numReviews: 9,
      ciuntInStock: 20,
      description: "A popular slim pants",
    },
  ],
};
export default data;
